spring.application.name=Sistema_agendamento_poli

server.servlet.context-path=/sistema_agendamento_poli

spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_agendamento_poli
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true