graph TD

%% -------------------- Atores --------------------
    subgraph  Atores
        Admin((Administrador))
        Professor((Professor))
        Aluno((Aluno))
    end

%% -------------------- Tela inicial e navegação --------------------
    subgraph  Tela Inicial
        inicial[tela inicial]
        login[tela de login]
        visualizar_mapa[Visualizar mapa do Politécnico]
        inicial --> login
        inicial --> visualizar_mapa
        Admin--> inicial
        Professor--> inicial
        Aluno--> inicial
    end

%% -------------------- Busca e visualização --------------------
    subgraph  Busca e Visualização de Salas
        buscar_sala[Buscar sala por nome ou código]
        visualizar_sala[Visualizar a agenda de uma sala]
        inicial --> buscar_sala
        buscar_sala --> visualizar_sala

    end

%% -------------------- Agendamento --------------------
    subgraph  Agendamento e Permissões
        pedir_agendamento[Pedir agendamento]
        decisao_analisar[Analisar pedido]
        agendar[Agendar sala]

        Aluno --> pedir_agendamento
        Admin --> decisao_analisar
        Professor --> agendar
        Admin --> agendar
    end

%% -------------------- Notificações --------------------
    subgraph  Notificações
        notificacoes[tela de notificações]
        login --> notificacoes
    end

