graph TB
%% -------------------- LOGÍSTICO --------------------
    subgraph Logístico
        l1["1 - Fazer o diagrama de casos de uso"]
        l2["2 - Fazer o modelo ER"]
        l3["3 - Fazer o termo de abertura do projeto"]
        l4["4 - Fazer o README para o github"]
        l5["5 - Criar a estrutura inicial de pastas do projeto"]
        l6["6 - Fazer o prototipo da  tela inicial"]
        l7["7 - Fazer o prototipo da  tela especifica de cada sala"]
        l8["8 - Fazer o prototipo da tela de notificacoes"]
        l9["9 - Mapear todas as salas do poli"]
        l10["10 - Fazer o protótipo da pagina de login"]

    %% dependências logístico
        l2 --> l5
    end

%% -------------------- BACKEND --------------------
    subgraph BackEnd
        b1["1 - Desenvolver Agenda Model"]
        b2["2 - Desenvolver AgendaDTO"]
        b3["3 - Desenvolver AgendaMapper"]
        b4["4 - Desenvolver AgendaRepository"]
        b5["5 - Desenvolver AgendaService"]
        b6["6 - Desenvolver AgendaController"]

        b7["7 - Desenvolver PedidoAgenda Model"]
        b8["8 - Desenvolver PedidoAgendaDTO"]
        b9["9 - Desenvolver PedidoAgendaMapper"]
        b10["10 - Desenvolver PedidoAgendaRepository"]
        b11["11 - Desenvolver PedidoAgendaService"]
        b12["12 - Desenvolver PedidoAgendaController"]

        b13["13 - Desenvolver Sala Model"]
        b14["14 - Desenvolver SalaDTO"]
        b15["15 - Desenvolver SalaMapper"]
        b16["16 - Desenvolver SalaRepository"]
        b17["17 - Desenvolver SalaService"]
        b18["18 - Desenvolver SalaController"]

        b19["19 - Desenvolver UsuarioDTO"]
        b20["20 - Desenvolver UsuarioMapper"]
        b21["21 - Desenvolver UsuarioRepository"]
        b22["22 - Desenvolver UsuarioService"]
        b23["23 - Desenvolver UsuarioController"]

        b24["24 - Desenvolver Usuario Model"]
        b25["25 - Desenvolver TipoUsuario"]
        b26["26 - Desenvolver StatusPedido"]
        b27["27 - Desenvolver StatusAgenda"]
        b28["28 - Desenvolver PermissaoNegadaException"]
        b29["29 - Desenvolver SalaIndisponivelException"]
        b30["30 - Desenvolver HorarioUtils"]

        b31["31 - Testar os endpoints"]
        b32["conectar front e back end"]

        b33["fazer um banco de dados que simule o do poli"]
        b34["conectar os bancos de dados ao back end, e fazer os primeiros migrations"]

    %% dependências agenda
        l2-->b1
        b1 --> b4
        b4 --> b5
        b5 --> b2
        b2 --> b3
        b3 --> b6
        b6 --> b31

    %% dependências pedidoagenda
        l2-->b7
        b7 --> b10
        b10 --> b11
        b11 --> b8
        b8 --> b9
        b9 --> b12
        b12 --> b31

    %% dependências sala
        l2-->b13
        b13 --> b16
        b16 --> b17
        b17 --> b14
        b14 --> b15
        b15 --> b18
        b18 --> b31

    %% dependências usuario
        l2-->b24
        b24 --> b21
        b21 --> b22
        b22 --> b19
        b19 --> b20
        b20 --> b23
        b23 --> b31

    %% dependencias geral
        b24 --> b25
        b7 --> b26
        b1 --> b27
        b22 --> b28
        b5 --> b29
        b1 --> b30
        b5 --> b30
        b33 --> b34
        b34 -->b31
        l2-->b34
    end


%% -------------------- FRONTEND --------------------
    subgraph FrontEnd
        f21["21 - Fazer o front end da tela inicial"]
        f22["22 - Fazer o front end da tela  especifica de cada sala"]
        f23["23 - Fazer o front end da tela  de notificacao"]
        f24["24 - Fazer o front end da tela de login/cadastro"]
        f25["25 - Fazer o mecanismo de alteracao de modo claro para modo escuro"]

    %% dependências frontend
        l6 --> f21
        l7 --> f22
        l8 --> f23
        l10 --> f24

    %% 25 depende de TODO o FrontEnd (21..24)
        f21 --> f25
        f22 --> f25
        f23 --> f25
        f24 --> f25
    end

%%outras dependencias
    b31-->b32
    f25 --> b32